### ISSUE TITLE
Windows Error 

### ISSUE THREAD

**Issue by sriosara** [utec/geofrontend-server#11]
TypeError: path must be absolute or specify root to res.sendFile
   at ServerResponse.sendFile (D:\temp\node_modules\express\lib\response.js:425:11)
   at D:\temp\node_modules\geofrontend-server\server\StaticServerConfigurator.js:75:11
   at Layer.handle [as handle_request] (D:\temp\node_modules\express\lib\router\layer.js:95:5)
   at next (D:\temp\node_modules\express\lib\router\route.js:137:13)
   at BasicSecurityStrategy.ensureAuthenticated (D:\temp\node_modules\geofrontend-server\basic-security-client\BasicSecurityStrategy.js:                   18:14)
   at SecurityConfigurator.hasProtectedAccess (D:\temp\node_modules\geofrontend-server\security\SecurityConfigurator.js:48:28)
   at hasProtectedAccess (D:\temp\node_modules\geofrontend-server\server\StaticServerConfigurator.js:20:30)
   at Layer.handle [as handle_request] (D:\temp\node_modules\express\lib\router\layer.js:95:5)
   at next (D:\temp\node_modules\express\lib\router\route.js:137:13)
   at Route.dispatch (D:\temp\node_modules\express\lib\router\route.js:112:3)

**Comment by jrichardsz** [comment]
https://github.com/utec/geofrontend-server/pull/14
